package(default_visibility = ["//visibility:public"])

filegroup(
    name = "alpha_jks",
    srcs = [
        "Alpha.jks",
    ],
)

filegroup(
    name = "beta_jks",
    srcs = [
        "Beta.jks",
    ],
)

filegroup(
    name = "boss_jks",
    srcs = [
        "Boss.jks",
    ],
)

filegroup(
    name = "trusted_jks",
    srcs = [
        "Trusted.jks",
    ],
)
