package(default_visibility = ["//visibility:public"])

filegroup(
    name = "alpha_keystore",
    srcs = [
        "Alpha.p12",
    ],
)

filegroup(
    name = "beta_keystore",
    srcs = [
        "Beta.p12",
    ],
)

filegroup(
    name = "boss_keystore",
    srcs = [
        "Boss.p12",
    ],
)

filegroup(
    name = "trusted_keystore",
    srcs = [
        "Trusted.p12",
    ],
)
